---
# tasks file for ansible-role-huggingbench

# Check for required Ansible and Python versions
- name: Run pre-checks
  ansible.builtin.import_tasks: precheck.yml

# Download and install HuggingBench tool
- name: Install prerequisites packages
  ansible.builtin.import_tasks: huggingbench.yml
